### ISSUE TITLE
Ability to mark all previous versions of the crate as insecure

### ISSUE THREAD

**Issue by dpc** [dpc/crev#163]
When an security vouln. is fixed, it would be great to create just one crate review that marks all previous versions as potentially insecure.

**Comment by dpc** [comment]
What I'm thinking about:


Command to mark a version as containing a security fix:

```
cargo crev review --security-fix <crate> [<version>]
```

That would mean, any/any major/any minor version is potentially affected.

In the proof it will look like this:

```
security-fix: <range>
```

Where `<range>` can be one of: `all`, `major`, `minor`, `patch`. It is not as flexible, as full list of ranges that were affected, but that's usually hard to determine/reason about, and if necessary can be simulated by producing multiple proofs.

While I'm at it, I wonder if it would be worthwile to generalize the whole thing to mean "important fix/update". 

Sometimes there are important things totally borked in previous versions, and from the perspective of the downstream user, it can be all combined to one "just upgrade, trust me".

I need to think about terminology here. Maybe just `advisory: <range>`, or `fixes: <range>`, or `important-fix: <range>`.

**Comment by dpc** [comment]
```
advisory:
  range: <range>
  severity: <level>
```

**Comment by dpc** [comment]
```
version: -1
date: "2019-04-22T21:53:15.382584127-07:00"
from:
  id-type: crev
  id: ZLBAs8cpEy-sIP0ORhOzrxcBxVJQx4Ie6I-b5SLkXE4
  url: "https://github.com/dpc/crev-proofs-test"
package:
  source: "https://crates.io"
  name: base64
  version: 0.5.2
  digest: wMN3VR6EWaI5i7BCYScLsbC1irWcLsEc3TAouoaGoK8
review:
  thoroughness: none
  understanding: none
  rating: positive
advisory:
  affected: major
  critical: false
comment: "https://github.com/RustSec/advisory-db/blob/master/crates/base64/RUSTSEC-2017-0004.toml"
```

Landed in `master` along with `cargo crev query advisory [...]` and `cargo crev review <package> --advisory major`.
