### ISSUE TITLE
`cargo crev diff`

### ISSUE THREAD

**Issue by dpc** [dpc/crev#173]
Easily show a diff between:

* last reviewed version and now
* last trusted version and now
* two arbitrary versions

**Comment by dpc** [comment]
Pushed, in the basic versions at least. Still requires `--` for stuff like `-u`, but works OKish already. Waiting for help here https://github.com/TeXitoi/structopt/issues/153#issuecomment-502344845

**Comment by dpc** [comment]
I've pushed initial support for differential reviews:

```
-----BEGIN CREV PACKAGE REVIEW-----
version: -1
date: "2019-06-17T23:58:20.220399363-07:00"
from:
  id-type: crev
  id: FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE
  url: "https://github.com/dpc/crev-proofs"
package:
  source: "https://crates.io"
  name: byteorder
  version: 1.3.1
  revision: 64c03fb383289f8e42b2892bf72297879777a238
  digest: Zh-2Tbe325ObJ51-O46m-B4hT_WUMnK2GSJJXVNKpXg
package-diff-base:
  source: "https://crates.io"
  name: byteorder
  version: 1.2.7
  revision: bdcc6bf676a1ed17eae68257bfa4726a1f0ec068
  digest: tm4tSfypGXF8-ESvMqH9Pw76GxIDm1UPVFHWF6LUZq8
review:
  thoroughness: low
  understanding: medium
  rating: strong
comment: "Good test coverage, good documentation. LGTM"
-----BEGIN CREV PACKAGE REVIEW SIGNATURE-----
EmXHW3pQ8ZN-KM1AeJZrlUfMr94Y285qhNLBJQXtfxxsc4uFZd1JqeYb_G2mn_-CccXYp6zwbrxrIj3fADEFCQ                                                                         
-----END CREV PACKAGE REVIEW-----
```
