### ISSUE TITLE
Should `advisories` be inclusive?

### ISSUE THREAD

**Issue by dpc** [dpc/crev#183]
Right now the advisory is filled in the first crate version that is fixed. However in practice, many crates do not have a fixed version yet, or even ever, when the authors refuse to fix them. So there is no version to fill the advisory for.

**Comment by dpc** [comment]
One way to approach this would be to have `version` in `advisories` be optional.

Another to have the `range: all` setting.

**Comment by dpc** [comment]
I thought about `version` being optional ,or `range:all`, but the problem with them is they are not immutable. If the problem is solved, one would have to go back and overwrite them.

So some form of inclusive behavior is better, because it basically never stops being true. The problem with is though is that advisory like that would have to be repeated repeatedly if the mainstream author keeps releasing unfixed versions. But I think it's more robust then the alternatives. Also, `crev` could smartly detect previously reported opened-ended advisories with no solutions, and consider them potentially still active.

So the question  now is - how to name the field exactly.

```
patched: false
```

`solved`? `fixed`?

?

**Comment by dpc** [comment]
So the plan is to overhaul much more than that.

First `rating: dangerous` is overlapping with what advisories are doing.  So it will be removed.

Instead new section will be added:

```
issues:
  - ids:
    - RUSTSEC-1342
      CVE-12345
      https://github.com/foo/bar/issue/234
    critical: true
    comment: "Buffer overflow" 
  - ids:
    - https://github.com/foo/bar/issue/123
    comment: "Writing to a file not atomic"
```

In issues it's possible to list one or more problems with the crate. Multipe ids are supported, but they are all considered the same underlying issue. If more issues are present - they should be split.

A version for which issue is reported does not have to be the first affected version. It only have to be affected by it. But an issue does imply that probably following versions are also affected.

The counter-part of "open issues" is `advisory` that basically closes the issue with the first version that fixes it.

```
advisories:
  - ids
    - RUSTSEC-1342
      CVE-12345
    critical: true
    comment: "Multiple buffer overflow"
```

Using `ids` `crev` will be able to match the `issues` and `advisories` keep track of when a given `issue` is no longer an issue.
